version: '3'
services:
  dbdheovani:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'dacs2022'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3317:3306'
    expose:
      - '3317'
  webdacsdheovani:
    image: dheovanidacs2022:latest
    depends_on:
      - "dbdheovani"
    ports:
      - "8092:8081"
    environment:
      - DB_HOST=dbdheovani:3317
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=dacs2022
      - SPRING_PROFILES_ACTIVE=prod