# @name loginAPI
POST http://localhost:8081/api/v1/auth/signin 
content-type: application/json

{
    "user": "admin",
    "password": "admin"
}

###

@token = {{loginAPI.response.body.*}}

###

GET http://localhost:8081/api/v1/procedure
Authorization: Bearer {{token}}

###

GET http://localhost:8081/api/v1/procedure/title/M
Authorization: Bearer {{token}}

###

GET http://localhost:8081/api/v1/procedure/2
Authorization: Bearer {{token}}

###

POST http://localhost:8081/api/v1/procedure
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Teste",
    "description": "Descricao"
}

###

PUT http://localhost:8081/api/v1/procedure/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Teste 2",
    "description": "Descricao 2"
}

###

DELETE http://localhost:8081/api/v1/procedure/3
Authorization: Bearer {{token}}
