# @name loginAPI
POST http://localhost:8081/api/v1/auth/signin 
content-type: application/json

{
    "user": "admin",
    "password": "admin"
}

###

@token = {{loginAPI.response.body.*}}

###

GET http://localhost:8081/api/v1/city
Authorization: Bearer {{token}}

###

GET http://localhost:8081/api/v1/city/name/Jo
Authorization: Bearer {{token}}

###

GET http://localhost:8081/api/v1/city/2
Authorization: Bearer {{token}}

###

POST http://localhost:8081/api/v1/city
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Joinville",
    "sex": "SC"
}

###

PUT http://localhost:8081/api/v1/city/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Blumenau",
    "sex": "SC"
}

###

DELETE http://localhost:8081/api/v1/city/2
Authorization: Bearer {{token}}
