# @name loginAPI
POST http://localhost:8081/api/v1/auth/signin 
content-type: application/json

{
    "user": "admin",
    "password": "admin"
}

###

@token = {{loginAPI.response.body.*}}

###

GET http://localhost:8081/api/v1/doctor
Authorization: Bearer {{token}}

###

GET http://localhost:8081/api/v1/doctor/name/M
Authorization: Bearer {{token}}

###

GET http://localhost:8081/api/v1/doctor/1
Authorization: Bearer {{token}}

###

POST http://localhost:8081/api/v1/doctor
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Ramon Victor",
    "crm": 4459
}

###

PUT http://localhost:8081/api/v1/doctor/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Melissa Nied",
    "crm": 389
}

###

DELETE http://localhost:8081/api/v1/doctor/1
Authorization: Bearer {{token}}
