GET http://localhost:8081/api/v1/patients

###

GET http://localhost:8081/api/v1/patients/name/ze

###

POST http://localhost:8081/api/v1/patients
Content-Type: application/json

{
    "name": "ZEZINHO",
    "sex": "MASC",
    "birthDate": "2022-08-17T00:00:00"
}